---
title: "Data Analysis"
author: "Shaun Jackson, Marissa Chemotti"
date: "7/3/2019"
output: 
  rmdformats::material:
    self_contained: no
---

```{r setup, include=FALSE}
options(stringsAsFactors = FALSE)
library(kableExtra)
adosm1 <- read.csv('./datasets/adosm1_scored.csv', stringsAsFactors = FALSE)
```

# Data Analysis

## Basic Stats functions

### Mean, Median, Standard Deviation, Summary
```{r}

mean(cars$speed, na.rm = TRUE)
median(cars$dist, na.rm = TRUE)
sd(cars$speed, na.rm = TRUE)

summary(cars)
```

## Linear Regression

- We will use the mtcars dataset for these examples

### Correlation

- Find correlation between two vars
```{r}
cor.test(mtcars$wt, mtcars$disp)
```

### Creating a Linear Model
```{r}
linearMod <-lm(dist ~ speed, cars)
print(linearMod)
```

### Plotting the Linear Model
```{r}
# create effects object
eff <- effects::Effect('speed', linearMod)
eff
plot(eff)
```

## Logistic Regression

```{r}
adosm1$ASD_risk <- as.factor(adosm1$recruitment_group == 'ASD risk')
adosm1$sarb_f <- as.factor(adosm1$ados_sarb_total)
adosm1$gender_factor <- as.factor(adosm1$gender)
adosm1$recruitment_group_f <- as.factor(adosm1$recruitment_group)
logMod <- 
  glm(ASD_risk ~ sarb_f +  gender_factor,
      adosm1, family = 'binomial')
logMod

plot(effects::Effect(c('sarb_f', 'gender_factor'), logMod))
```


## Mixed Effects Models

## Plotting with effects

## Plotting with ggplot

## More Resources

